import type { SiteContent } from "./types";

export const localContent: SiteContent = {
  contact: {
    phone: "0800-123-456",
    phoneHref: "tel:0800123456",
    line: "@petoxyhome",
    lineHref: "https://line.me/R/ti/p/@petoxyhome",
    email: "service@petoxy-home.com",
    address: "台中市西屯區寵愛路 88 號",
    hours: "週一至週日 09:00 - 21:00（節慶不打烊）",
  },
  products: [
    {
      slug: "everflo",
      name: "EverFlo「磊仕」氧氣濃縮機",
      label: "經典居家型",
      image: "/images/everflo.png",
      rent: 2500,
      noise: "約 45 dBA（典型值）",
      license: "衛署醫器輸字第 018363 號",
      sourceUrl: "https://www.yongyuemedical.com/product_d.php?lang=tw&tb=1&id=272",
      description: "穩定、耐用的居家型氧氣濃縮機，可提供長時間連續供氧。機身設計緊湊、操作直覺，適合依獸醫師建議，搭配寵物氧氣箱進行居家照護。",
      highlights: ["24 小時連續供氧", "低耗能、低熱量設計", "整合式流量計", "居家照護操作直覺"],
    },
    {
      slug: "everflo-q",
      name: "EverFlo Q「磊仕」氧氣濃縮機",
      label: "靜音升級型",
      image: "/images/everflo-q.jpg",
      rent: 3000,
      noise: "約 40 dBA（典型值）",
      license: "衛部醫器輸字第 026412 號",
      sourceUrl: "https://www.yongyuemedical.com/product_d.php?lang=tw&tb=1&id=110",
      description: "承襲 EverFlo 的穩定供氧能力，並針對運轉聲進一步優化。較安靜的使用感受，適合對聲音敏感、需要長時間休息的毛孩與居家環境。",
      highlights: ["靜音運轉設計", "24 小時連續供氧", "小體積、方便移動", "減少休息時的聲音干擾"],
    },
  ],
  commonSpecs: [
    ["氧氣濃度", "93% ± 3%（5 L/min 時）"],
    ["流量範圍", "0.5–5 L/min"],
    ["機身尺寸", "高 58.4 × 寬 38.1 × 深 24.1 cm"],
    ["重量", "約 14 kg"],
    ["平均耗電", "約 350 W"],
    ["輸出壓力", "5.5 PSI"],
    ["電源", "120V ± 10% AC／60 Hz（依實際租借機標示）"],
    ["操作高度", "海拔 0–2,286 m"],
  ],
  faqs: [
    { category: "使用需求", question: "什麼情況下需要幫毛孩使用氧氣機？", answer: "常見情況包括心臟病（如二尖瓣閉鎖不全）、慢性肺部疾病、氣管塌陷、術後恢復期，以及高齡犬貓因心肺功能退化而出現呼吸急促、活動力下降等情形。建議先諮詢獸醫師，確認毛孩是否適合居家氧氣照護。" },
    { category: "使用需求", question: "沒有獸醫師處方也可以租借氧氣機嗎？", answer: "可以租借，但我們強烈建議在使用前諮詢獸醫師，了解適合的氧氣濃度與使用時間。我們的客服人員也會於租借諮詢時，協助了解毛孩狀況並提供基本操作說明。" },
    { category: "租借相關", question: "租借需要負擔哪些費用？", answer: "EverFlo 標準型每月 NT$3,000，EverFlo Q 靜音型每月 NT$3,500。押金、運送及到府服務費用會依地區與實際方案確認，請聯繫客服為您試算。" },
    { category: "租借相關", question: "租借期間設備故障怎麼辦？", answer: "如遇設備異常，請立即停止使用並聯繫我們。我們會先協助確認警示與操作狀況，並視情況安排檢修或更換備用機，降低照護中斷的時間。" },
    { category: "操作使用", question: "氧氣機的噪音會不會讓毛孩緊張？", answer: "EverFlo 運轉音量約 45 dBA；EverFlo Q 為較安靜的機型，約 40 dBA。每隻毛孩對聲音的敏感度不同，我們會提供漸進式適應與設備擺放建議。" },
    { category: "操作使用", question: "使用氧氣機需要每天更換耗材嗎？", answer: "不需要每天更換。濾網與管路的清潔、更換頻率會依使用時間與環境空氣品質而異，請依原廠說明及租借時提供的保養指引操作。" },
    { category: "安全注意", question: "居家使用氧氣機有沒有危險性？", answer: "氧氣具有助燃性，設備應遠離吸菸、明火、香氛蠟燭、油脂與高溫電器，並保持散熱空間。到府安裝時會說明擺放與使用注意事項。" },
    { category: "安全注意", question: "毛孩使用氧氣機時可以離開視線嗎？", answer: "建議照護初期全程陪伴觀察，並依獸醫師建議安排使用時間。即使熟悉操作後，也應透過透明艙體或監視設備隨時留意呼吸、精神與體溫狀況。" },
  ],
  blogPosts: [
    { slug: "cat-heart-care", category: "疾病照護", readTime: "4 分鐘閱讀", title: "貓咪心臟病居家照護：氧氣治療的時機與注意事項", excerpt: "貓咪的心臟病往往初期症狀不明顯，一旦出現呼吸急促、張口呼吸，可能已是中後期警訊。本文帶你了解何時該考慮居家氧氣照護。", date: "2026-05-12" },
    { slug: "post-op-care", category: "術後照護", readTime: "3 分鐘閱讀", title: "毛孩術後恢復期：氧氣艙如何協助康復進程", excerpt: "術後的黃金恢復期，穩定的氧氣環境能提供呼吸支持。整理術後居家照護的三個關鍵重點。", date: "2026-04-28" },
    { slug: "senior-dog-breathing", category: "高齡照護", readTime: "3 分鐘閱讀", title: "老犬呼吸變化觀察指南：這些徵兆別忽略", excerpt: "隨著年紀增長，狗狗的心肺功能會自然退化。學會觀察呼吸頻率與型態的變化，能及早發現需要協助的訊號。", date: "2026-03-15" },
  ],
};
