import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { CTA, PageHero, SectionHeading } from "@/components/site-shell";
import { getSiteContent } from "@/lib/content";
export const metadata: Metadata = {
  title: "產品介紹",
  description: "EverFlo 與 EverFlo Q 寵物氧氣濃縮機規格、租金與差異比較，提供 93% ± 3% 穩定氧氣濃度，適合心臟病、肺部疾病、術後恢復與高齡毛孩居家照護。",
};
export default async function Products() { const content = await getSiteContent(); return <><PageHero eyebrow="產品介紹" title="為毛孩挑選合適的居家氧氣設備" text="目前提供 EverFlo 與 EverFlo Q 兩款氧氣濃縮機。規格透明、機型清楚，方便依照護環境與聲音敏感度選擇。" /><section className="section"><div className="container product-list">{content.products.map((p,i)=><article className="product-detail glass-panel" key={p.slug}><div className="product-detail-image"><span className="product-tag">{p.label}</span><Image src={p.image} alt={p.name} width={630} height={520}/></div><div className="product-detail-copy"><span className="eyebrow">機型 {i+1}</span><h2>{p.name}</h2><p>{p.description}</p><div className="spec-chips"><span>氧氣濃度 93% ± 3%</span><span>流量 0.5–5 L/min</span><span>{p.noise}</span></div><ul className="check-list">{p.highlights.map(x=><li key={x}>✓ {x}</li>)}</ul><div className="price-box"><span>月租方案</span><strong>NT$ {p.rent.toLocaleString()}</strong><small>／月</small></div><p className="license">醫療器材許可證：{p.license}</p><div className="button-row"><Link className="button primary" href="/contact">諮詢這款機型</Link><a className="source-link" href={p.sourceUrl} target="_blank" rel="noreferrer">查看參考機型來源 ↗</a></div></div></article>)}</div></section><section className="section soft-section"><div className="container"><SectionHeading eyebrow="共同規格" title="EverFlo 系列技術規格" text="不同電壓、地區與實際租借機型可能略有差異，請以機身標示與原廠說明書為準。" /><div className="spec-table">{content.commonSpecs.map(([k,v])=><div key={k}><span>{k}</span><strong>{v}</strong></div>)}</div><p className="medical-note">本設備為醫療器材。毛孩的氧氣濃度、流量與使用時間應由獸醫師依病況評估。</p></div></section><CTA lineHref={content.contact.lineHref}/></> }
